BRONZE_DAG_ID = "subscription_events_bronze_ingestion"
SILVER_DAG_ID = "subscription_events_silver_transform"
GOLD_KPI_DAILY_DAG_ID = "subscription_events_gold_kpi_daily"

DEFAULT_BRONZE_BASE_DIR = "/opt/project/data/bronze/subscription_events"
DEFAULT_SILVER_HISTORY_DIR = "/opt/project/data/silver/subscription_state_history"
DEFAULT_SILVER_CURRENT_DIR = "/opt/project/data/silver/subscription_state_current"
DEFAULT_SILVER_CURRENT_PATH = "/opt/project/data/silver/subscription_state_current/current.parquet"
DEFAULT_GOLD_KPI_DAILY_DIR = "/opt/project/data/gold/kpi_daily"
DEFAULT_PIPELINE_STATE_DIR = "/opt/project/data/state/pipeline"
DEFAULT_GENERATOR_SEQ_PATH = "/opt/project/data/state/generator/last_subscription_seq.txt"
DEFAULT_GENERATOR_STATE_CURRENT_PATH = "/opt/project/data/state/generator/subscription_state_current.json"