BRONZE_DAG_ID = "subscription_events_bronze_ingestion"
SILVER_DAG_ID = "subscription_events_silver_transform"
GOLD_KPI_DAILY_DAG_ID = "subscription_events_gold_kpi_daily"

EC2_DATA_ROOT = "/opt/project/data"
TEST_ROOT = "/Users/soomin/workspace/saas-subscription-lifecycle/data"

DEFAULT_BRONZE_BASE_DIR = "bronze/subscription_events"
DEFAULT_SILVER_HISTORY_DIR = "silver/subscription_state_history"
DEFAULT_SILVER_CURRENT_DIR = "silver/subscription_state_current"
DEFAULT_SILVER_CURRENT_PATH = "silver/subscription_state_current/current.parquet"
DEFAULT_GOLD_KPI_DAILY_DIR = "gold/kpi_daily"
DEFAULT_PIPELINE_STATE_DIR = "state/pipeline"
DEFAULT_GENERATOR_SEQ_PATH = "state/generator/last_subscription_seq.txt"
DEFAULT_GENERATOR_STATE_CURRENT_PATH = "state/generator/subscription_state_current.json"