name: Deploy Airflow (EC2)

on:
  push:
    branches:
      - main
    paths:
      - "dags/**"
      - "plugins/**"
      - "src/**"
      - "docker-compose.airflow.yml"
      - "infra/ansible/**"
      - ".github/workflows/deploy-airflow.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Create inventory for CI
        run: |
          cat <<EOF > inventory.ci.ini
          [airflow]
          airflow1 ansible_host=${{ secrets.EC2_HOST }} ansible_user=${{ secrets.EC2_USER }} ansible_ssh_private_key_file=~/.ssh/id_ed25519
          EOF

      - name: Run deploy playbook
        run: |
          ansible-playbook -i inventory.ci.ini infra/ansible/playbooks/deploy-airflow.yml